### ISSUE TITLE
nlarn crashes when trying to start up.

### ISSUE THREAD

**Issue by rschmetzer** [nlarn/nlarn#301]
Running on Windows 10 x64.  I get the greetings page and after passing that the program thinks it sees a corrupted save file.  I can't bypass this message without the program crashing.

**Comment by jaydg** [comment]
Hi! Can you please attach the save file to this issue, I can then try to reproduce the crash. 

You can find the file in the directory %LOCALAPPDATA%\nlarn

**Comment by rschmetzer** [comment]
Here ya go.
[nlarn.zip](https://github.com/nlarn/nlarn/files/7014503/nlarn.zip)

**Comment by jaydg** [comment]
I checked out your savegame. It was created by version 0.7.2 and thus isn't compatible with the current version, which is 0.7.6. Unfortunately, I'm even unable to build that old version with the current environments - which means I am unable to look into your issue. Whatever causes the crash - we'll never know. 

The current version is eight (!) years younger than the version you are playing and contains a lot of fixes since that really old version. I suggest you get the current version, it even looks much nicer than that old version. You'll find it here: https://nlarn.github.io/news/2020/05/23/release-0.7.6

Thanks anyway for creating this issue, I shall be glad to leard about any troubles with the current version.

**Comment by rschmetzer** [comment]
Thanks.  I wasn't aware of that.  I don't even remember downloading the
old version.  I recently downloaded and installed the new version but I
guess the old save file was still there.
